API_KEY="88iBd1SmUZCSTcdn6y2l"
AWS_ACCESS_KEY = 'AKIAWOOXTZCT3MX3QT6R'
AWS_SECRET_KEY = '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'
S3_BUCKET_NAME = 'safetyviolations'
VIOLATION_COOLD = 3  # Seconds between uploads